name: Docker Image CI/CD

on:
  push:
    branches: [ "main" ]
    paths:
      - 'Dockerfile'
      - 'config/**'
      - '.github/workflows/**'
  workflow_dispatch:

env:
  DOCKERHUB_IMAGE_NAME: mmr757/seanime
  GITHUB_IMAGE_NAME: mmrmagno/seanime

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get current date
        id: date
        run: echo "date=$(date +'%Y%m%d')" >> $GITHUB_OUTPUT

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            mmr757/seanime:latest
            mmr757/seanime:${{ steps.date.outputs.date }}
            ghcr.io/mmrmagno/seanime:latest
            ghcr.io/mmrmagno/seanime:${{ steps.date.outputs.date }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            BUILD_DATE=${{ steps.date.outputs.date }}
            VERSION=${{ github.sha }}

      - name: Sync README to DockerHub
        uses: ms-jpq/sync-dockerhub-readme@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: mmr757/seanime
          readme: ./README.md
